### ISSUE TITLE
NullReferenceException while trying to execute sample code

### ISSUE THREAD

**Issue by JamesMaloney** [SharpSenses/SharpSenses#9]
Whenever I try to execute the sample code:

var cam = Camera.Create(Capability.HandTracking);
    cam.LeftHand.Visible += (s,a) => Console.WriteLine("Hi left hand!");
    cam.RightHand.Closed += (s,a) => Console.WriteLine("Hand Closed");
    cam.RightHand.Moved += (s,a) => {
        Console.WriteLine("-> x:{0} y:{1}", a.Position.Image.X, a.Position.Image.Y);
    };
    cam.Start();

The software gets immediately stuck at the first line, saying "System.NullReferenceException: 'Object reference not set to an instance of an object.'"

Is there anything I missed?

**Comment by andrecarlucci** [comment]
Hi James,
This repo is for the Intel RealSense Camera, with the RealSense SDK version 10. 
This is quite old, to be honest, I don't even think that they sell that camera anymore.
Are you using exactly this?

**Comment by JamesMaloney** [comment]
Well, those names are kind of confusing to me.
I have an Intel RealSense D435 Camera, which should be supported (?) and the most recent RealSense SDK v2.
I suppose they changed nomenclature at some point since I can't see how version 10 can be older than current v2.
Anyway, if SharpSenses devices are not supported anymore, I will try some other alternatives.
Thank you very much for your time!

**Comment by andrecarlucci** [comment]
Any time! 
I will add a big line alerting people about it, thanks for reaching out.
Cheers.
